name: 'Read JS Files'
description: 'To Read multiple JS files and send it as a list of contents'
inputs:
  directoryPath:
    description: 'path to script directory'
    required: true
  
runs:
  using: "composite"
  steps:        
    - name: Run Node Script
      run: |
        git clone https://github.com/CodexStorm/Upload-Workflows.git --depth 1
        cd Upload-Workflows
        npm i
        npm run build
        cp -R ../${{ inputs.directoryPath }} ${{ inputs.directoryPath }}
        node index.js ${{ inputs.directoryPath }} > temp
        cat temp
      shell: bash