name: 'Read JS Files'
description: 'To Read multiple JS files and send it as a list of contents'
inputs:
  directoryPath:
    description: 'path to script directory'
    required: true
  
runs:
  using: "composite"
  steps:        
    - name: Run Node Script
      run: |
        git clone https://github.com/CodexStorm/Upload-Workflows.git
        cd Upload-Workflows
        npm i
        node index.js
      shell: bash