name: 'Read JS Files'
description: 'To Read multiple JS files and send it as a list of contents'
inputs:
  directoryPath:
    description: 'path to script directory'
    required: true
  
runs:
  using: "composite"
  steps:        
    - name: Run Node Script
      run: |
        node index.js
      shell: bash